packages/website/index.html, packages/website/src/components/Hero.tsx, packages/website/src/components/Nav.tsx, packages/website/src/components/NextPrevPage.tsx, packages/website/src/components/Note.tsx, packages/website/src/components/PageContent.tsx, packages/website/src/components/PageTitle.tsx
Removes dark mode until color variables are usable via the tailwind config. Until then the experience is not good enough because there are missing color changes.
=> chore: remove dark mode

packages/website/package.json, packages/website/src/components/ChatConfiguration.tsx, packages/website/src/components/MultimodalConfiguration.tsx, packages/website/src/components/Ui.tsx, packages/website/src/constants.ts, packages/website/src/content/06-01-multimodal-setup.tsx, packages/website/src/content/06-03-multimodal-try-live.tsx, packages/website/src/routes.tsx, packages/website/src/snippets.ts
Add a widget setup-like page for voice compass / multimodal journeys.
=> Multimodal setup page

packages/voice-compass/src/index.ts
- **drop changeJourney api**
- **consume context type**
- **drop session code**
- **inline sendUpdateRequest**
- **remove `currentJourneyId`**
=> further simplify voice compass api

packages/website/src/routes.tsx
@sam-trost  and I discussed this in order to unblock releasing the website ASAP.
=> hide voice compass documentation until it's up to date

.github/workflows/publish-website.yml
=> use node-version-file for publish website

.github/workflows/test-on-push.yml, package.json, packages/voice-compass/jest.config.ts, packages/voice-compass/package.json, packages/voice-compass/src/index.ts, packages/voice-compass/tests/index.test.ts
adds a regression test & fixes step id regex
=> fix step verification

packages/chat-widget/src/ui/components.tsx
Make sure lists are rendered with the appropriate chat bubbles.
=> Render lists in chat bubble

package.json, packages/website/README.md
follow-up to #31 with a tiny bit of documentation cc @peterszerzo
=> document updating typedoc

packages/chat-widget/src/icons.tsx, packages/chat-widget/src/index.tsx, packages/chat-widget/src/props.ts, packages/website/src/content/02-04-web-widget-try-live.tsx
Add both minimize and close buttons, with the following functionalities:
- minimize simply closes the chat box.
- close clears and resets the conversation, additionally.
=> Add separate collapse and close buttons

packages/chat-core/package.json, packages/chat-core/tsconfig.json, packages/chat-preact/package.json, packages/chat-preact/tsconfig.json, packages/chat-react/package.json, packages/chat-react/tsconfig.json, packages/chat-widget/package.json, packages/chat-widget/tsconfig.json, packages/eslint-config-nlx/index.js, packages/eslint-config-nlx/package.json, packages/voice-compass/package.json, packages/voice-compass/tsconfig.json, packages/website/package.json, packages/website/tsconfig.json
small ~ useful cleanups from #35
=> mild cleanups

packages/chat-core/src/index.ts, packages/eslint-config-nlx/package.json, packages/website/src/snippets.ts
starting point for better docs
tsdoc / jsdoc is there to allow generated docs + more readable code. 
this is one step towards more readable code.
=> resolve eslints for cleaner documentation palette

packages/chat-widget/src/ui/components.tsx
Fix spacing and padding glitches inside the message bubbles.
=> Spacing updates

package-lock.json, packages/chat-core/src/index.ts, packages/website/package.json, packages/website/src/components/ChatConfiguration.tsx, packages/website/src/content/02-01-web-widget-setup.tsx, packages/website/src/content/02-03-web-widget-custom-behaviors.tsx, packages/website/src/content/02-04-web-widget-try-live.tsx, packages/website/src/content/03-01-web-widget-components-getting-started.tsx
small code change while I'm writing documentation
feel free to review them commit-by-commit
1. simplify implementation of `shouldReinitialize` to make clear what fields are included / excluded from the logic.
2. ensure `nlx-api-key` is actually required
(I will keep adding small changes to this PR as I see them in the documentation PR / until this PR is merged)
=> small api changes

packages/chat-widget/src/ui/components.tsx
- add underline to links.
- tweak spacings.
=> Style updates

flake.nix, packages/website/Caddyfile, packages/website/README.md, packages/website/package.json
adds a github-pages like environment for the website using caddy
=> add caddy for local testing of github pages

packages/chat-core/src/index.ts
Implements https://nlx-ai.atlassian.net/browse/DSP-406.
=> Add SDK version in HTTP request header

packages/chat-core/src/index.ts
two small follow-ups from #55, #50
- fix  a bug in `promisify`
- change reinitialize logic
=> small sdk tweaks

packages/chat-core/package.json, packages/chat-core/src/index.ts, packages/chat-widget/.eslintrc.cjs, packages/chat-widget/.gitignore, packages/chat-widget/package.json, packages/chat-widget/src/icons.tsx, packages/chat-widget/src/index.tsx, packages/chat-widget/src/props.ts, packages/chat-widget/src/theme.ts, packages/chat-widget/src/types.d.ts, packages/chat-widget/src/ui/components.tsx, packages/chat-widget/src/ui/constants.ts, packages/chat-widget/src/utils.ts, packages/chat-widget/tsdoc.json, packages/chat-widget/typedoc.cjs, packages/eslint-config-nlx/documentation.js, packages/voice-compass/package.json, packages/website/src/content/02-04-web-widget-try-live.tsx
document the widget api (and a handful of other small changes)
this PR does not publish the docs in the website yet
=> document widget api

packages/chat-widget/src/index.tsx, packages/chat-widget/src/types.d.ts, packages/chat-widget/src/ui/components.tsx, packages/website/index.html, packages/website/src/content/02-04-web-widget-try-live.tsx, packages/website/src/custom-components/Payment.tsx
Disable the input field if the last payload contains `nlx:input-disabled=true`
=> Add disabled input feature

.github/workflows/publish-website.yml, package-lock.json, packages/website/package.json, packages/website/render-static.ts, packages/website/src/components/Header.tsx, packages/website/src/vite-env.d.ts
add search using Algolia's DocSearch.
... this took far less time than I was expecting
~~# ❌ todo before merge:~~
✅  @vlad31 did this
add vars to github
and secrets:
we can iterate on design, search performance later
=> add search

lerna.json, package-lock.json, packages/journey-manager/.eslintrc.cjs, packages/journey-manager/.gitignore, packages/journey-manager/.npmignore, packages/journey-manager/LICENSE, packages/journey-manager/package.json, packages/journey-manager/rollup.config.mjs, packages/journey-manager/src/index.ts, packages/journey-manager/src/queries.ts, packages/journey-manager/tsconfig.json, packages/journey-manager/tsdoc.json, packages/journey-manager/typedoc.cjs, packages/voice-compass/jest.config.ts, packages/voice-compass/tsconfig.dev.json, packages/voice-compass/tsconfig.json, packages/voice-compass/typedoc.cjs
Alternative to #60, with linting and tsdoc.
=> Journey manager package

packages/journey-manager/src/index.ts, packages/website/src/snippets.ts
Naive implementation of digression detection.
=> Digression callback

packages/website/src/content/07-03-journey-manager-query-engine.tsx, packages/website/src/routes.tsx
I don't know if this is the most suitable place, but I feel like users should have access to this in one place or another (or at least our own staff).
=> Adds some conceptual documentation to the query engine

packages/journey-manager/src/index.ts, packages/journey-manager/src/queries.ts
Closes #76.
Also removes the query suggestion code from the package and makes the types a bit nicer.
=> Minor SDK refactoring

packages/website/src/content/02-03-web-widget-custom-behaviors.tsx, packages/website/src/content/07-01-journey-manager-getting-started.tsx, packages/website/src/snippets.ts
https://github.com/nlxai/sdk/assets/6738398/aeb6bc7e-564d-4ba6-87e9-1764908b6e7e
=> Expand on snippets

packages/chat-widget/src/index.tsx
Sessions should only persist if the bot and the language are the same.
=> Separate sessions across bots and languages

packages/website/src/content/02-04-web-widget-try-live.tsx, packages/website/src/content/05-01-headless-getting-started.tsx, packages/website/src/snippets.ts
- send welcome intent on the widget try page.
- add headless code example.
=> Documentation page updates

packages/chat-widget/src/ui/components.tsx, packages/chat-widget/src/ui/constants.ts
- responsiveness fixes.
- typography improvements.
=> Redesign nudge

packages/chat-widget/src/ui/components.tsx
This seems to be a more reliable fix in practice
=> Hard-codes an input color

packages/journey-manager/src/index.ts, packages/journey-manager/src/ui.ts, packages/website/src/content/04-03-react-api-reference.md, packages/website/src/content/04-04-preact-api-reference.md, packages/website/src/content/05-02-headless-api-reference.md, packages/website/src/content/06-03-multimodal-api-reference.md, packages/website/src/content/07-02-journey-manager-api-reference.md
Implements https://linear.app/nlxai/issue/FRO-7/journey-manager-ui-prototype
=> Set up journey manager UI

packages/journey-manager/src/index.ts
=> Fix triggers retrieve method

packages/journey-manager/src/index.ts
=> Position journey manager custom element as absolute

packages/journey-manager/src/index.ts
Fixes https://linear.app/nlxai/issue/FRO-30/handle-previous-step-button-in-control-center-ui.
=> Redirect if the previous step happened on a different URL

packages/journey-manager/src/index.ts, packages/journey-manager/src/ui.tsx
Allow a customizable `onPreviousStep` behavior.
=> Journey manager hooks

packages/journey-manager/src/ui.tsx
If the element changes, positions need to be recomputed.
=> Recompute journey manager highlights on element change

packages/eslint-config-nlx/index.js, packages/website/src/components/InlineWidget.tsx, packages/website/src/components/NextPrevPage.tsx, packages/website/src/components/PageContent.tsx, packages/website/src/custom-components/FileUpload.tsx
follow up from https://github.com/nlxai/dialog-studio-frontend/pull/430#discussion_r1642663431
cc @jakub-nlx
=> allow nullable booleans

packages/chat-widget/package.json, packages/website/src/content/02-05-web-widget-api-reference.md, packages/website/src/content/02-05-web-widget-api-reference.tsx, packages/website/src/routes.tsx
the api reference material was almost all previously set up. This just publishes it to the developer page.
=> add web widget api references

packages/chat-preact/src/index.ts, packages/chat-react/src/index.ts
Removing some unnecessary clear-and-reset code for the React and Preact packages.
=> Remove unnecessary response state reset

package-lock.json, packages/journey-manager/package.json, packages/journey-manager/src/ui.tsx, packages/website/src/components/Prototyping.tsx
Fixes https://linear.app/nlxai/issue/FRO-34/solidify-highlights-implementation.
https://github.com/nlxai/sdk/assets/6738398/a6170ce1-6698-43c7-a0b4-6073fc050ec3
=> highlights follow u around 👻

packages/journey-manager/src/ui.tsx, packages/website/src/components/Prototyping.tsx
Fixes https://linear.app/nlxai/issue/FRO-72/journey-manager-control-center-button-ux.
https://github.com/user-attachments/assets/ebc9217d-5915-410f-bdde-6238106d8f8d
=> Improve control panel UX

package-lock.json, packages/eslint-config-nlx/package.json, packages/rollup-config-nlx/package.json
while playing with peer dependencies to reproduce user issues, I made this small improvement
=> internal tools have dependencies not peer dependencies

packages/journey-manager/src/index.ts, packages/journey-manager/src/ui.tsx
after feedback from floating-ui team, this is another approach for #126 / FRO-34
see: https://github.com/floating-ui/floating-ui/pull/2974
also: take it or leave it!
=> simpler solution for highlights following you around

package.json, packages/chat-core/README.md, packages/chat-core/package.json, packages/chat-core/src/index.ts, packages/chat-preact/package.json, packages/chat-preact/src/index.ts, packages/chat-react/package.json, packages/chat-react/src/index.ts, packages/chat-widget/package.json, packages/journey-manager/package.json, packages/multimodal/package.json, packages/website/src/snippets.ts, test-repos/chat-core/browser-test.html, test-repos/chat-core/package-lock.json, test-repos/chat-core/package.json, test-repos/chat-core/src/index.cjs, test-repos/chat-core/src/index.mjs, test-repos/chat-core/src/index.ts, test-repos/chat-core/tsconfig.json
addresses https://github.com/nlxai/sdk/issues/122
this is mergable. in a follow-up PR i'd like to add automated tests that load up a browser
addresses FRO-62 with some non-covering  integration tests
=> test repo & ensure we build for every type

packages/journey-manager/src/index.ts
Implements https://github.com/nlxai/nlx/pull/1232
=> Implements smart match and regex

packages/journey-manager/src/ui.tsx, packages/website/src/components/Prototyping.tsx
FRO-76, 
mostly moved nudge logic & styling over from the chat widget
=> FRO 76 show hide tooltip

packages/journey-manager/src/index.ts, packages/journey-manager/src/ui/components/index.tsx, packages/journey-manager/src/ui/custom-element.tsx, packages/journey-manager/src/ui/index.tsx, packages/journey-manager/src/ui/style.css
- fix control center confirmation alignment
- refactor and persist nudge state
=> Journey Manager fixes

package-lock.json, packages/chat-core/src/index.ts
Allow the client to override the bot request, sending the data somewhere else.
=> Request overrides

packages/journey-manager/src/ui/components/index.tsx, packages/website/src/components/Prototyping.tsx
https://github.com/user-attachments/assets/1cd14973-9621-4215-88ea-691274bc9623
=> Add confirmation to custom buttons

packages/journey-manager/src/ui/custom-element.tsx, packages/journey-manager/src/ui/index.tsx
Also does a little more refactoring just for good measure.
=> Makes trigger highlights stop if once

packages/website/src/components/Header.css, packages/website/src/custom-components/SecureInput.css
Fixes https://nlxai.slack.com/archives/C01RGUJ519V/p1724975783699589.
=> Form fixes

packages/journey-manager/src/ui/components/index.tsx, packages/journey-manager/src/ui/style.css
- close control center on click outside.
- some CSS fixes.
=> Journey manager control center UX upgrades

packages/chat-core/src/index.ts
Allow language switching during a conversation.
Fixes https://linear.app/nlxai/issue/FRO-478/allow-language-switching-in-nlxaichat-core.
=> Language switching

packages/touchpoint-ui/src/App.tsx, packages/touchpoint-ui/src/components/ChatHeader.tsx, packages/touchpoint-ui/src/components/ChatInput.tsx, packages/touchpoint-ui/src/components/ChatMessages.tsx, packages/touchpoint-ui/src/components/ChatSettings.tsx, packages/touchpoint-ui/src/components/ui/Loader.tsx, packages/touchpoint-ui/src/context.ts, packages/touchpoint-ui/src/design-system.tsx, packages/touchpoint-ui/src/index.css, packages/touchpoint-ui/src/types.ts, packages/touchpoint-ui/tailwind.config.js
Fixes https://linear.app/nlxai/issue/DSP-1748/touchpoints-feedback.
=> Touchpoint QA round 1

packages/touchpoint-ui/src/components/ui/Loader.tsx, packages/touchpoint-ui/src/design-system.tsx
The main trick was that your original implementation had separate easing for each animation step, but Kuba's had a single easing for the entire movement of the balls.
https://github.com/user-attachments/assets/2c53929d-45a3-4a96-81ef-7b8566366093
Video on top, animation below.
=> Adjusts easing

package-lock.json, packages/touchpoint-ui/index.html, packages/touchpoint-ui/package.json, packages/touchpoint-ui/src/components/ui/DateInput.tsx, packages/touchpoint-ui/src/components/ui/TextButton.tsx, packages/touchpoint-ui/src/design-system.tsx
- docs for masking: https://www.npmjs.com/package/@react-input/mask
- had to run `format` that's why index changed
- `disabled` state done
- `pressed` isn't (https://www.figma.com/design/8Oaes7pyKPxz79ASIOxHPP?node-id=198-7792&m=dev#1089290102)
- fixed `active` state on textbutton
=> feat: add a date input component

packages/website/src/constants.ts, packages/website/src/content/01-01-getting-started.tsx, packages/website/src/content/01-02-installation.tsx
* Adds packageUrls.touchpointUi to constants for website
* Adds npmUrls for each package for future usage
* Adds deprecation warning for chat-widget
=> add touchpoint-ui installation details

packages/touchpoint-ui/src/App.tsx, packages/touchpoint-ui/src/components/ChatHeader.tsx, packages/touchpoint-ui/src/components/ChatInput.tsx, packages/touchpoint-ui/src/components/ChatMessages.tsx, packages/touchpoint-ui/src/components/ChatSettings.tsx, packages/touchpoint-ui/src/components/Theme.tsx, packages/touchpoint-ui/src/components/ui/CustomCard.tsx, packages/touchpoint-ui/src/components/ui/DateInput.tsx, packages/touchpoint-ui/src/components/ui/IconButton.tsx, packages/touchpoint-ui/src/components/ui/LaunchButton.tsx, packages/touchpoint-ui/src/components/ui/PicturesContainer.tsx, packages/touchpoint-ui/src/components/ui/TextButton.tsx, packages/touchpoint-ui/src/components/ui/ViewMediaModal.tsx, packages/touchpoint-ui/src/design-system.tsx, packages/touchpoint-ui/src/types.ts, packages/touchpoint-ui/tailwind.config.js
Add launch icon and brand icon support to Touchpoint.
Fixes https://linear.app/nlxai/issue/FRO-614/add-touchpoint-logo-to-button-in-collapsed-mode.
https://github.com/user-attachments/assets/bbbe6c13-2427-46b3-a9fb-cf7d4b288831
=> Add icon support to launch button

packages/chat-core/src/index.ts, packages/touchpoint-ui/src/App.tsx, packages/touchpoint-ui/src/components/FullscreenError.tsx, packages/touchpoint-ui/src/components/Header.tsx, packages/touchpoint-ui/src/components/Input.tsx, packages/touchpoint-ui/src/components/Messages.tsx, packages/touchpoint-ui/src/components/Settings.tsx, packages/touchpoint-ui/src/index.css, packages/website/src/content/02-03-touchpoint-ui-try-live.tsx
Fixes https://linear.app/nlxai/issue/FRO-621/full-screen-error-page.
=> Full-screen error page

packages/touchpoint-ui/src/index.tsx, packages/touchpoint-ui/src/preview.tsx
This in support of the UI editor for touchpoint components.
=> Adds preview component to support editor

packages/website/package.json
Nice for instance for making markdown tables aligned automatically.
=> Adds prettier for website formatting

packages/website/src/content/01-01-getting-started.tsx, packages/website/src/content/02-02-touchpoint-ui-theming.md, packages/website/src/content/02-03-touchpoint-ui-ConversationHandler.md, packages/website/src/content/03-01-touchpoint-components.md, packages/website/src/content/03-02-touchpoint-Typography.md, packages/website/src/content/03-03-touchpoint-Buttons.md, packages/website/src/content/03-04-touchpoint-CustomCards.md, packages/website/src/content/03-05-touchpoint-Icons.md, packages/website/src/content/03-06-touchpoint-DateInput.md
Small Docs Cleanup PR
* Remove beta from intro page
* Add links to HTM building from each component
* Add ToC to Touchpoint docs
See [Staging Site](https://staging.d264tx1fb5x21o.amplifyapp.com/)
=> Small Docs Cleanup

.gitignore, packages/touchpoint-ui/.gitignore, packages/touchpoint-ui/index.html, packages/touchpoint-ui/package.json, packages/touchpoint-ui/src/App.tsx, packages/touchpoint-ui/src/components/ui/CustomCard.tsx, packages/touchpoint-ui/src/components/ui/DateInput.tsx, packages/touchpoint-ui/src/components/ui/IconButton.tsx, packages/touchpoint-ui/src/components/ui/Icons.tsx, packages/touchpoint-ui/src/components/ui/TextButton.tsx, packages/touchpoint-ui/src/index.tsx, packages/touchpoint-ui/typedoc.cjs, packages/website/src/content/02-05-touchpoint-ui-api-reference.tsx, packages/website/src/content/headless-api-reference.md, packages/website/src/content/preact-api-reference.md, packages/website/src/content/react-api-reference.md, packages/website/src/content/script-manager-api-reference.md, packages/website/src/content/touchpoint-ui-api-reference.md, packages/website/src/content/voice-plus-api-reference.md, packages/website/src/content/web-widget-api-reference.md
Adds 
* Types and exports to props interfaces 
* typedoc configuration
*  typedoc generation to package.json
* Git Ignore deploy_staging scripts
* Git Ignore temporary docs folder from typedoc output
=> DEV-18: TypeDoc for Touchpoint-UI

package-lock.json, packages/touchpoint-ui/index.html, packages/touchpoint-ui/src/App.tsx, packages/touchpoint-ui/src/components/Header.tsx, packages/touchpoint-ui/src/components/Input.tsx, packages/touchpoint-ui/src/components/Messages.tsx, packages/touchpoint-ui/src/index.tsx, packages/touchpoint-ui/src/types.ts
Also adds a few minor features such as disabling the touchpoint or handling the close button in a custom way.
Also stops changing behavior in dev mode.
=> Adds embedded mode to touchpoint UI

package-lock.json, packages/chat-widget/src/props.ts, packages/website/src/components/Hero.tsx, packages/website/src/components/TouchpointComponents/IconButton.tsx, packages/website/src/components/TouchpointDemoAnimation.tsx
- limit animation height.
- improve mobile view.
- fix docs link per https://nlxai.slack.com/archives/C03M8DM13QQ/p1743772553277709.
=> Hero banner adjustments

package-lock.json, packages/chat-core/src/index.ts, packages/touchpoint-ui/index.html, packages/touchpoint-ui/package.json, packages/touchpoint-ui/src/App.tsx, packages/touchpoint-ui/src/components/Input.tsx, packages/touchpoint-ui/src/components/ui/IconButton.tsx, packages/touchpoint-ui/src/globals.d.ts, packages/touchpoint-ui/src/types.ts, packages/touchpoint-ui/src/voice.ts, test-repos/chat-core/package-lock.json
Fixes https://linear.app/nlxai/issue/FRO-657/touchpoint-voice-frontend.
How to test / run locally:
- `npm install` top level
- `cd packages/touchpoint-ui`
- `npm run dev`
Edit the `packages/touchpoint-ui/index.html` file for application credentials and testing code.
=> Voice in Touchpoint

package-lock.json, packages/chat-core/package.json, packages/chat-core/rollup.config.ts, packages/chat-preact/package.json, packages/chat-preact/rollup.config.ts, packages/chat-react/package.json, packages/chat-react/rollup.config.ts, packages/chat-widget/package.json, packages/chat-widget/rollup.config.ts, packages/rollup-config-nlx/package.json, packages/voice-plus-core/package.json, packages/voice-plus-core/rollup.config.ts, packages/voice-plus-web/package.json, packages/voice-plus-web/rollup.config.ts
=> Fixes build on node >=22

packages/touchpoint-ui/index.html, packages/touchpoint-ui/src/App.tsx, packages/touchpoint-ui/src/components/FullscreenError.tsx, packages/touchpoint-ui/src/components/FullscreenVoice.tsx, packages/touchpoint-ui/src/components/Input.tsx, packages/touchpoint-ui/src/components/Ripple.tsx, packages/touchpoint-ui/src/components/ui/Icons.tsx, packages/touchpoint-ui/src/components/ui/LaunchButton.tsx, packages/touchpoint-ui/src/types.ts, packages/touchpoint-ui/src/voice.ts
=> Voice-only mode

package-lock.json, packages/touchpoint-ui/src/App.tsx, packages/touchpoint-ui/src/components/Messages.tsx, packages/touchpoint-ui/src/index.css, packages/touchpoint-ui/src/types.ts
Fixes https://linear.app/nlxai/issue/FRO-872/touchpoint-markdown-styling-review.
=> Touchpoint styling

package-lock.json, packages/touchpoint-ui/src/voice.ts, packages/website/src/components/Toggle.tsx, packages/website/src/content/02-04-touchpoint-ui-try-live.tsx
- debounces speaker state changes.
- add input mode toggle:
=> Voice improvements

packages/website/src/components/ChatConfiguration.tsx, packages/website/src/content/02-01-touchpoint-ui-try-live.tsx
Fixes https://linear.app/nlxai/issue/FRO-874/support-setting-userid-on-touchpoint-try-live-page.
=> Add userId configuration to Touchpoint try now page

packages/website/src/content/02-01-touchpoint-ui-try-live.tsx, packages/website/src/snippets.ts
try it live now updates both snippet and functionality for colorMode(light|dark) and input(voice|text)
=> Try it live with colorMode and (voice) input toggle

packages/touchpoint-ui/src/App.tsx, packages/website/src/content/02-01-touchpoint-ui-try-live.tsx
Add launch icon to all modes including voice mini.
=> Improve voice mini entry point

packages/chat-core/src/index.ts, packages/touchpoint-ui/src/App.tsx, packages/touchpoint-ui/src/components/FullscreenVoice.tsx, packages/touchpoint-ui/src/components/VoiceMini.tsx, packages/touchpoint-ui/src/index.tsx, packages/touchpoint-ui/src/types.ts, packages/touchpoint-ui/src/voice.ts, test-repos/chat-core/package-lock.json
You'd add an `initialContext` parameter to the touchpoint config.
=> Adds context to voice in touchpoint

packages/touchpoint-ui/src/App.tsx, packages/touchpoint-ui/src/components/FullscreenVoice.tsx, packages/touchpoint-ui/src/voice.ts
Fixes FRO-940, and FRO-928 (albeit with a temporary UI):
=> Handle disconnect better

packages/touchpoint-ui/src/App.tsx, packages/touchpoint-ui/src/components/FullscreenVoice.tsx, packages/touchpoint-ui/src/components/Header.tsx, packages/touchpoint-ui/src/components/VoiceMini.tsx, packages/touchpoint-ui/src/index.tsx, packages/touchpoint-ui/src/types.ts
- mute speakers button in fullscreen mode.
- fixes https://linear.app/nlxai/issue/FRO-1028/add-red-x-to-indicate-call-termination-clearly.
- close button for voice mini.
=> Voice fixes

packages/website/src/content/02-02-touchpoint-ui-setup.md, packages/website/src/content/02-03-touchpoint-ui-theming.md, packages/website/src/content/02-04-guide-touchpoint-chat-modes.md, packages/website/src/content/02-05-touchpoint-ui-voice.md, packages/website/src/content/03-01-touchpoint-ui-ConversationHandler.md, packages/website/src/content/03-03-guide-custom-launch.md, packages/website/src/content/03-04-guide-subscribing-to-events.md, packages/website/src/content/03-05-guide-show-hide-touchpoint.md, packages/website/src/content/03-06-guide-persisting-history.md, packages/website/src/content/05-00-guide-building-custom-components.md, packages/website/src/content/05-01-touchpoint-carousel.md, packages/website/src/content/05-02-touchpoint-Typography.md, packages/website/src/content/05-03-touchpoint-Buttons.md, packages/website/src/content/05-04-touchpoint-CustomCards.md, packages/website/src/content/05-05-touchpoint-Icons.md, packages/website/src/content/05-06-touchpoint-DateInput.md
See [Staging](https://staging.d264tx1fb5x21o.amplifyapp.com/) for Example rendering:
=> Devx 46 code tabs

packages/touchpoint-ui/src/components/FullscreenVoice.tsx
Might be overkill but I don't think it's right to leave the context out here.
=> Initialize with context

packages/touchpoint-ui/index.html, packages/touchpoint-ui/src/App.tsx, packages/touchpoint-ui/src/components/FullscreenVoice.tsx, packages/touchpoint-ui/src/components/Messages.tsx, packages/touchpoint-ui/src/components/VoiceMini.tsx, packages/touchpoint-ui/src/components/ui/IconButton.tsx, packages/touchpoint-ui/src/voice.ts
- fixes https://github.com/nlxai/sdk/issues/274.
- fixes https://linear.app/nlxai/issue/PRO-3736/cant-close-touchpoint-mini.
https://github.com/user-attachments/assets/9ecbf930-e2bd-4200-b662-c1e6d2cbb5d7
=> Closable touchpoint mini

packages/touchpoint-ui/src/voice.ts
Fixes https://linear.app/nlxai/issue/PRO-3709/touchpoint-still-listening-when-closed.
=> Improve track handling

packages/touchpoint-ui/index.html, packages/touchpoint-ui/src/App.tsx, packages/touchpoint-ui/src/components/FullscreenVoice.tsx, packages/touchpoint-ui/src/components/VoiceMini.tsx, packages/touchpoint-ui/src/voice.ts
Attempt to fix https://linear.app/nlxai/issue/PRO-3910/bypass-the-soundcheck-screen-on-voice.
Current issue: cannot get the voice permissions dialog back on retry:
https://github.com/user-attachments/assets/dd309ebc-afa5-49bf-96af-747b0314e805
=> Attempt at simplifying voice

packages/website/src/content/02-06-touchpoint-voice-plus.md, packages/website/src/content/02-06-touchpoint-voice-plus.tsx
Fixes hello world and better headings to match expected XP
[Staging Site](https://staging.d264tx1fb5x21o.amplifyapp.com/touchpoint-voice-plus)
=> update v+ docs

.github/workflows/create-release-pr.yml, .github/workflows/release.yml, package.json
Let's see how well this works.
=> Attempt to use CI for release flow

packages/touchpoint-ui/src/components/FullscreenVoice.tsx, packages/touchpoint-ui/src/components/VoiceMini.tsx, packages/touchpoint-ui/src/components/ui/Carousel.tsx, packages/touchpoint-ui/src/components/ui/CustomCard.tsx, packages/touchpoint-ui/src/components/ui/DateInput.tsx, packages/touchpoint-ui/src/components/ui/Typography.tsx, packages/touchpoint-ui/src/types.ts, packages/touchpoint-ui/src/voice.ts
https://github.com/user-attachments/assets/c7538a11-ad34-4de0-99d1-97bd4cfcc8ea
https://github.com/user-attachments/assets/574f4b0d-f2f7-47e7-8f7b-f9e3f63bc29d
=> Keep track of modalities histories

packages/touchpoint-ui/src/components/defaultModalities/DefaultCard.tsx, packages/touchpoint-ui/src/components/defaultModalities/DefaultCarousel.tsx, packages/touchpoint-ui/src/components/defaultModalities/DefaultDateInput.tsx, packages/touchpoint-ui/src/components/defaultModalities/shared.ts, packages/touchpoint-ui/src/components/defaultModalities/types.ts, packages/touchpoint-ui/src/index.tsx
https://github.com/user-attachments/assets/9935e7c7-bf81-4a8f-911a-9db0165c9e3c
=> Set up custom modalities

package-lock.json, packages/cli/package.json, packages/cli/src/commands/data-requests/index.ts, packages/cli/src/commands/data-requests/sync.ts, packages/cli/src/commands/login.ts, packages/cli/src/commands/modalities.ts, packages/cli/src/index.ts, packages/cli/src/utils/index.ts
=> Adds an oas import command

lerna.json, package-lock.json, package.json, packages/cli/__tests__/data-requests/sync.test.ts, packages/cli/__tests__/modalities/generate.test.ts, packages/cli/package.json, packages/touchpoint-ui/package.json, packages/website/package.json
Updates mostly vite + Lerna. Removes some unused deps.
Doesn't fix the `moderate` vulnerability existing on prismjs since that isn't updated in the dependency we're using and I could for the life of me not get the overrides feature to work.
=> Fixes security vulnerabilities

packages/touchpoint-ui/src/App.tsx, packages/touchpoint-ui/src/components/RiveAnimation.tsx
https://github.com/user-attachments/assets/201921ad-f60f-4a25-a14f-3790d8d8d6dd
=> Sets the rive color to --accent
