packages/chat-core/src/index.ts, packages/website/src/snippets.ts
- fix script indentation.
- fix umd script url.
- fix version number.
=> Fix widget snippet

packages/chat-widget/src/types.d.ts, packages/chat-widget/tsconfig.json
npx tsc now compiles the chat widget
=> make typescript compile

packages/voice-compass/src/index.ts, packages/voice-compass/tsconfig.json
a handful of small changes to the voice compass API. Want to sync with @sam-trost about these
These are all good, but talking to Sam, I'd like to try scrapping most of this API and making it much much simpler. 
from my understanding: Voice Compass used to model a state machine internally, but now requires the user to model the state machine. Considering that: I think the small complexity around state management can go away and can be modeled in the documentation. So while this PR is probably a bunch of baby steps in the right direction, the subsequent PR will try trimming the library down to the bare minimum
=> small voice compass changes

packages/website/src/snippets.ts
Need to add this semicolon so that if the customer puts the script in one line, the javascript interpreter doesn't get weird.
@michaelglass @jakub-nlx merging this right away because it is urgent for a user.
=> Add semicolon to message check script in chat widget

packages/chat-core/src/index.ts, packages/chat-widget/src/index.tsx, packages/chat-widget/src/props.ts
New widget configuration option to enable the behavior that does not disable choice buttons once a selection is made, allowing the selection to be changed later on.
=> Allow choice reselection option for chat widget

packages/chat-core/src/index.ts
While the frontend should support both arrays and objects for slots in terms of API, the backend should always be sent arrays.
=> Normalize slots dictionary as array

packages/chat-widget/src/index.tsx
Add a `console.warn` in case there is a modality that is sent by the backend but not implemented in the frontend. Credit to @RomanistNLX for the idea.
=> Add warning if modality is not implemented

packages/chat-widget/src/index.tsx
Although new tab links degrade UX in a lot of cases, the chat widget is an appropriate exception: navigating to a new page while the widget is open risks losing chat state, especially if local storage cannot be used or if the retrieval implementation comes with edge cases.
=> Open markdown links in new tab by default

packages/website/404.html, packages/website/index.html, packages/website/package.json, packages/website/src/main.tsx
mislead by dev environment differing from prod environment.
Github Actions doesn't rewrite URLs on refresh, so using BrowserRouter meant loading, e.g. `/foo` would just 404.
This PR
- adds a custom 404.html that redirects folks back to `/index` with the path in the query string
- adds some logic to index.html that parses the parses the path out of the query string. 
- adds a caddy dev environment that should mimick github actions
I feel mixed about this PR. On the one hand, I think BrowserRouter produces prettier URLs and most importantly, those URLs support on-page anchor tags (needed for #31 ) But on the other hand, this PR is a bit of a hack and abuses the 404 page.
other solutions:
- static rendering (might help with SEO, e.g. right now google doesn't have any deep links into …
=> support browser router on github pages

flake.nix, package-lock.json, packages/chat-core/.eslintrc.cjs, packages/chat-core/.gitignore, packages/chat-core/README.md, packages/chat-core/package.json, packages/chat-core/src/index.ts, packages/chat-core/tsdoc.json, packages/chat-core/typedoc.cjs, packages/eslint-config-nlx/documentation.js, packages/voice-compass/package.json, packages/voice-compass/src/index.ts, packages/voice-compass/typedoc.cjs, packages/website/src/content/05-02-headless-api-reference.md, packages/website/src/content/05-02-headless-api-reference.tsx, packages/website/src/content/06-03-multimodal-api-reference.md
flesh out tsdoc for chat-core library
I'm unhappy with the formatting & ordering of the auto-generated docs.
Some options:
- stop using markdown rendering, and render typedoc natively to html on a different domain, e.g. `api.developers.nlx.ai`
- use typedoc to render to json, and write our own typedoc renderer to handle formatting & ordering ourself
- manually massage the markdown output until it looks more acceptable.
=> document core chat api

package-lock.json, packages/website/package.json, packages/website/render-static.ts, packages/website/src/components/Header.tsx, packages/website/src/custom-components/Disclaimer.tsx, packages/website/src/entry-client.tsx, packages/website/src/static-renderer.tsx, packages/website/tsconfig.json, packages/website/vite.config.ts
before resolving other errors, I want the baseline number of errors to be zero.
this PR resolves...
- errors in dev about not hydrating (because dev doesn't use static rendering or a server)
- errors on both because of keying (I don't exactly know why this happened but I made react happy anyways)
- errors in production because of failed hydration (because the SSR version didn't render DocSearch so the doms were different)
=> resolve noisey errors

packages/chat-widget/src/ui/components.tsx
Fixes the above issue caused when the browser is switched to dark mode. The root cause is of course that the input doesn't have an explicit color set, but I'd rather not mess with that at the moment, since it's not clear to me that it would work with the background the users can control, and this way it can be overriden with CSS if need be.
=> Forces chat widget to light mode

packages/journey-manager/src/index.ts
```
loadSteps.forEach(({ stepId, urlCondition, once }) => {
if (urlCondition != null && !matchesUrlCondition(urlCondition)) {
return;
}
sendStep(stepId, once ?? false);
});
```
`once ?? false` always resolving to false because trigger's `once` value isn't being captured. 
Capture `trigger.once` value during `loadSteps` array creation
=> Adding trigger "once" value into loadSteps

packages/chat-core/src/index.ts
Resolve chat request promises on failure (not just on proper bot response)
=> Fix promisify wrapper

package-lock.json, packages/journey-manager/package.json, packages/journey-manager/src/index.ts, packages/journey-manager/src/ui.ts, packages/website/src/content/04-03-react-api-reference.md, packages/website/src/content/04-04-preact-api-reference.md, packages/website/src/content/05-02-headless-api-reference.md, packages/website/src/content/06-03-multimodal-api-reference.md, packages/website/src/content/07-02-journey-manager-api-reference.md
Fixes https://linear.app/nlxai/issue/FRO-17/pulsing-highlights-on-journey-manager.
@jakub-nlx this removes `findActiveTriggers` from the public API as it becomes internal to the package. So we can improve on the implementation later without having the end user have to change anything. Lame 500ms setInterval-based implementation for now, but only triggers if highlights are enabled.
https://github.com/nlxai/sdk/assets/6738398/d40a1677-ba1c-47cb-933f-88b256eb13e5
=> Add trigger highlights

packages/journey-manager/src/index.ts
@jakub-nlx also resolves your previous feedback about the `DOMContentLoaded` event being moved inside the SDK method, this will allow the setup script to be a bit simpler.
=> Support hosted triggers

packages/journey-manager/src/index.ts, packages/website/package.json, packages/website/src/App.tsx, packages/website/src/components/Prototyping.tsx, packages/website/src/content/04-03-react-api-reference.md, packages/website/src/content/04-04-preact-api-reference.md, packages/website/src/content/05-02-headless-api-reference.md, packages/website/src/content/06-03-multimodal-api-reference.md, packages/website/src/content/07-02-journey-manager-api-reference.md, packages/website/src/routes.tsx
- add a mutation observer instance.
- use it to run URL change logic.
- use it to run highlights more efficiently (remove setInterval).
=> Add mutation observer

packages/journey-manager/src/index.ts, packages/website/src/components/Prototyping.tsx
Also includes some refactoring that fixes a click but related to the `once` feature.
=> Handle `appear` events

package-lock.json, packages/chat-core/src/index.ts, packages/chat-widget/src/index.tsx, packages/website/src/content/04-03-react-api-reference.md, packages/website/src/content/04-04-preact-api-reference.md, packages/website/src/content/05-02-headless-api-reference.md, packages/website/src/content/06-03-multimodal-api-reference.md, packages/website/src/content/07-02-journey-manager-api-reference.md
Providing this extra context with the request helps the NLU identify the node in question during conversation execution.
=> Send intentId to NLU

packages/chat-core/src/index.ts, packages/chat-widget/src/index.tsx
Expose helpers to figure out the current expiration timestamp of a conversation, allowing the user to handle it however they wish. Alternative to https://github.com/nlxai/sdk/pull/46.
```ts
const conversationHandler = nlxai.chatCore.create({ botUrl: "" });
conversationHandler.subscribe((responses) => {
const timestamp = nlxai.chatCore.getCurrentExpirationTimestamp(responses);
// Set timeouts, alerts etc.
});
```
=> Expiration helpers

packages/chat-widget/src/index.tsx
Soft-reset the conversation on timeout (keep history up to that point).
=> Expiration reset

packages/rollup-config-nlx/index.ts
I haven't tested this extensively (across other packagers, for instance) but it appears to at least work for journey manager
=> fix journey manager umd

package-lock.json, packages/journey-manager/package.json, packages/journey-manager/src/ui.tsx, packages/website/src/components/Prototyping.tsx
implements FRO-79
To the reviewer: should we stop creating a highlight element and ONLY style the existing element with a blinking drop shadow? Or will that be less compatible? I guess if we style the existing element, the element borders will be less janky (and in general, the complexity of the whole implementation should be simpler save for the one thousand edge cases)
=> prototype of outline-style highlight

packages/website/src/components/Prototyping.tsx
Helps with testing issues like these.
/cc @michaelglass
=> Adds a little testing helper for breaking stuff

packages/journey-manager/src/configuration.ts, packages/journey-manager/src/ui/components/HighlightOverlay.tsx, packages/journey-manager/src/ui/components/index.tsx, packages/journey-manager/src/ui/custom-element.tsx, packages/journey-manager/src/ui/global.css, packages/journey-manager/src/ui/highlightBoxShadow.ts, packages/journey-manager/src/ui/index.tsx, packages/journey-manager/src/utils/dom.ts, packages/website/src/components/Prototyping.tsx
This now seems to work in all the scenarios I could think of... So in this branch this strategy is enabled by default. However, you can change this default by passing `highlightStrategy: 'overlay'` to the config.
=> Adds a more robust box-shadow highlight strategy

package.json
I've often run `npm run watch` and have it not pick up changes.
This change has made it more reliable for me.
(once upon a time I did the research to know exactly why but I'm not spending the cycles right now. We can always roll back if it causes problems)
additionally I ignore building website from watch, because we use `npm run dev` for that
=> since head is more reliable for me than --since

packages/touchpoint-ui/src/App.tsx, packages/touchpoint-ui/src/components/ChatInput.tsx, packages/touchpoint-ui/src/components/ChatMessages.tsx, packages/touchpoint-ui/src/components/ui/Loader.tsx
- improved loading animation.
- improved file upload UX.
- add scroll divider.
=> Touchpoint QA round 2

README.md, packages/chat-core/src/index.ts, packages/chat-widget/src/index.tsx, packages/chat-widget/src/theme.ts
Allows `applicationUrl` in the config, and renames instances of `"bot"` in the documentation (not the code or the types).
=> Application URL renames

packages/website/src/components/PageContent.tsx
I _guess_ this was a regression introduced in https://github.com/nlxai/sdk/commit/7be6c3d5c198069cb3b9d2a4553733b739e6bdb8 but I have no confirmed that.
The markdown code had named anchor tags that were stripped out.
After this commit, I believe markdown anchors work again.
=> fix markdown anchor links

packages/touchpoint-ui/src/components/Messages.tsx
Make sure there's spacing between multiple paragraphs:
=> Fix touchpoint paragraph spacing

packages/touchpoint-ui/src/App.tsx, packages/touchpoint-ui/src/index.tsx
Also fixes the issue where if you customized your conversation initialization script, it wouldn't be used on reset.
=> Stop sending welcome intent in voice

packages/website/src/content/02-01-touchpoint-ui-try-live.tsx, packages/website/src/useUrlState.ts
This means that reloading the touchpoint quick start won't loose your info, but also allows users to share a pre-configured Quick Start URL.
=> Adds URL persistance to config

packages/website/src/content/02-01-touchpoint-ui-try-live.tsx
Some browsers have an issue with frequent touchpoint widget re-initialization and crash the page.
Fixes https://linear.app/nlxai/issue/PRO-3855/touchpoint-dev-docs-try-live-page-crashes-on-color-selection.
=> Debounce touchpoint widget re-init

packages/touchpoint-ui/src/components/Header.tsx
I believe this should solve this minor positioning blunder:
=> Fix embedded layout

package-lock.json, packages/touchpoint-ui/package.json, packages/website/package.json, packages/website/src/components/PageContent.tsx, packages/website/src/content/02-10-touchpoint-ui-api-reference.tsx, packages/website/src/content/headless-api-reference.md, packages/website/src/content/preact-api-reference.md, packages/website/src/content/react-api-reference.md, packages/website/src/content/script-manager-api-reference.md, packages/website/src/content/touchpoint-ui-api-reference.md, packages/website/src/content/voice-plus-api-reference.md, packages/website/src/content/web-widget-api-reference.md, packages/website/src/index.css
There's certainly more that can be done here - I think there should be some improvements made with figuring out a more sensible order/structure to the docs.
But this seems to my eyes as much easier to browse, as it makes grouping and structure a lot easier to see (and also de-emphasizes the GitHub links).
=> Improve API reference docs styling

packages/touchpoint-ui/src/voice.ts
This fixes the awkward red/orange system microphone icon persisting even after disconnect.
https://stackoverflow.com/questions/42786056/removing-microphone-indicator-in-google-chrome
I think this PR could do with some extra testing making sure something else hasn't been borked.
=> Fixes microphone icon persisting

packages/touchpoint-ui/src/App.tsx, packages/touchpoint-ui/src/bidirectional/automaticContext.ts, packages/touchpoint-ui/src/bidirectional/commandHandler.ts, packages/touchpoint-ui/src/bidirectional/debug.ts, packages/touchpoint-ui/src/index.tsx, packages/touchpoint-ui/src/types.ts, packages/touchpoint-ui/src/voice.ts
The problem was on [this line](#diff-9f8226a4f6e54253f828f937acc5bf80d1e01c6a12c826bcc4708102b1078e5fR137), 
but the PR includes various other improvements, like a nice little tag for filtering logs which should make it easier to debug V+ interactions. Also fixes an issue with context being sent before the widget is opened.
=> Fixes various misconfiguration

packages/touchpoint-ui/index.html, packages/touchpoint-ui/src/App.tsx, packages/touchpoint-ui/src/bidirectional/automaticContext.ts, packages/touchpoint-ui/src/bidirectional/commandHandler.ts, packages/touchpoint-ui/src/components/FullscreenVoice.tsx, packages/touchpoint-ui/src/components/Header.tsx, packages/touchpoint-ui/src/components/Messages.tsx, packages/touchpoint-ui/src/components/Theme.tsx, packages/touchpoint-ui/src/components/VoiceMini.tsx, packages/touchpoint-ui/src/components/defaultModalities/DefaultCard.tsx, packages/touchpoint-ui/src/components/defaultModalities/DefaultCarousel.tsx, packages/touchpoint-ui/src/components/defaultModalities/DefaultDateInput.tsx, packages/touchpoint-ui/src/design-system.tsx, packages/touchpoint-ui/src/index.tsx, packages/touchpoint-ui/src/interface.ts, packages/touchpoint-ui/src/preview.tsx, packages/touchpoint-ui/src/types.ts, packages/touchpoint-ui/tsdoc.json
Adds:
- `ToucpointInstance.setCustomBidirectionalCommands` for automatic context bidi mode. 
- `config.bidirectional.customizeAutomaticContext` option for customizing what the automatic context does. I think we've seen the use for this kind of function before - where the automatic mode does 90% of what you need, but there is some small feature you'd like to cover.
- Automatic context now sends the `uri` parameter automatically.
=> Add way to define available custom actions and send them in
